import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const d2coding = localFont({
  src: [
    {
      path: "./fonts/D2Coding-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/D2Coding-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-d2coding",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: LayoutProps<"/">) => {
  return (
    <html
      lang="en"
      className={`${d2coding.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">{children}</body>
    </html>
  )
}

export default RootLayout;
